name: Deploy

on:
  push:
    branches: [ master ]



jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

    steps:
    - uses: actions/checkout@v2.3.4

    # - name: Install
    #   run: npm install

    # - name: Build assets
    #   run: npm run build

    - name: Sentry Release
      uses: getsentry/action-release@testing_env_input # Change the version for testing
      with:
        url_prefix: ~/static/js
        sourcemaps: build/static/js