name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Build assets
      run: sleep 0.5

    - name: Configure credentials
      run: sleep 0.1

    - name: Deploy to production
      run: sleep 1

    - name: Sentry Release
      uses: getsentry/action-release@bffb8e7497965880e4c2d206b74c469f616865c0 # Change the version for testing
      with:
        environment: production