name: Deploy

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Build assets
      run: sleep 0.5

    - name: Configure credentials
      run: sleep 0.1

    - name: Deploy to production
      run: sleep 1

    - name: Sentry Release
      uses: getsentry/action-release@5d9e70a28bba4c62ebca79bad210c228b0b82dbc # Change the version for testing
      with:
        environment: production
        url_prefix: ~/static/js
        sourcemaps: build/static/js