name: Deploy

on:
  push:
    branches: [ master ]



jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install
      run: npm install

    - name: Build assets
      run: npm run build

    - name: Sentry Release
      uses: getsentry/action-release@dfa5cdafefda80245d6bec5b14cc83ea531a67c8 # Change the version for testing
      with:
        environment: production
        url_prefix: ~/static/js
        sourcemaps: build/static/js
        version: v1.0